import assert from "node:assert/strict";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { applyTimelineEdit, newProject, saveProject } from "../scripts/project-store.mjs";
import { cancelExportJob, listExportJobs, readExportJob, submitExportJob } from "../scripts/export-job-engine.mjs";

const root = resolve(process.argv[2] || "/tmp/mycut-export-jobs"); rmSync(root, { recursive: true, force: true }); mkdirSync(root, { recursive: true }); const run = (command, args) => { const result = spawnSync(command, args, { encoding: "utf8" }); if (result.status !== 0) throw new Error(result.stderr); }; const source = `${root}/source.mp4`, projectPath = `${root}/export.mycut.json`; run("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc2=s=320x180:r=24:d=2", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=2", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", source]); const project = newProject({ name: "Export jobs", width: 320, height: 180, fps: 24 }); project.assets.push({ id: "source", path: source, name: "source", type: "video", duration: 2, width: 320, height: 180, hasAudio: true }); applyTimelineEdit(project, { trackName: "V1", adds: [{ assetId: "source", start: 0, sourceStart: 0, duration: 2 }] }); applyTimelineEdit(project, { trackName: "A1", adds: [{ assetId: "source", start: 0, sourceStart: 0, duration: 2 }] }); saveProject(projectPath, project);
const wait = async (id, expected = ["completed", "failed", "cancelled"]) => { const deadline = Date.now() + 30000; while (Date.now() < deadline) { const job = readExportJob(projectPath, id); if (expected.includes(job.status)) return job; await new Promise(resolveWait => setTimeout(resolveWait, 100)); } throw new Error(`Timed out waiting for ${id}`); };
let job = submitExportJob(projectPath, { kind: "video", outputPath: `${root}/background.mp4`, options: { burnCaptions: false, resolution: "480p", frameRate: 24 } }); assert.equal(job.status, "queued"); job = await wait(job.id); assert.equal(job.status, "completed"); assert.equal(job.progress, 100); assert.equal(job.result.probe.streams.find(stream => stream.codec_type === "video").height, 480); assert.equal(existsSync(job.outputPath), true);
job = submitExportJob(projectPath, { kind: "audio", outputPath: `${root}/mix.wav`, options: { format: "wav" } }); job = await wait(job.id); assert.equal(job.status, "completed"); assert.equal(job.result.probe.streams.some(stream => stream.codec_type === "video"), false);
job = submitExportJob(projectPath, { kind: "fcpxml", outputPath: `${root}/timeline.fcpxml` }); job = await wait(job.id); assert.equal(job.status, "completed"); assert.equal(existsSync(job.outputPath), true);
job = submitExportJob(projectPath, { kind: "unsupported", outputPath: `${root}/bad.out` }); job = await wait(job.id); assert.equal(job.status, "failed"); assert.match(job.error, /Unsupported export job kind/);
job = submitExportJob(projectPath, { kind: "video", outputPath: `${root}/cancelled.mp4` }); const cancelled = cancelExportJob(projectPath, job.id); assert.equal(cancelled.status, "cancelled"); assert.equal((await wait(job.id)).status, "cancelled"); assert.ok(listExportJobs(projectPath).length >= 5); assert.equal(listExportJobs(projectPath)[0].id, job.id); assert.throws(() => readExportJob(projectPath, "missing"), /not found/);
console.log(JSON.stringify({ ok: true, jobs: listExportJobs(projectPath).map(entry => ({ kind: entry.kind, status: entry.status, progress: entry.progress })), outputs: [`${root}/background.mp4`, `${root}/mix.wav`, `${root}/timeline.fcpxml`] }, null, 2));
