import assert from "node:assert/strict";
import { activeTimeline, applyTimelineEdit, newProject, validateProject } from "../scripts/project-store.mjs";
import { linkTimelineItems, moveLinkedGroup, placeLinkedAv, trimLinkedGroup, unlinkTimelineItems } from "../scripts/linked-clips-engine.mjs";

const project = newProject({ name: "Linked AV", width: 320, height: 180, fps: 30 }); project.assets.push({ id: "av", path: "/tmp/av.mp4", name: "Camera", type: "video", duration: 12, hasAudio: true }, { id: "bed", path: "/tmp/bed.wav", name: "Bed", type: "audio", duration: 12 }, { id: "still", path: "/tmp/still.png", name: "Still", type: "image", duration: null });
let placed = placeLinkedAv(project, { assetId: "av", videoTrackIdOrName: "V1", audioTrackIdOrName: "A1", mode: "append", sourceStart: 1, sourceEnd: 5, label: "Interview" }); assert.equal(placed.video.start, 0); assert.equal(placed.audio.start, 0); assert.equal(placed.video.sourceStart, 1); assert.equal(placed.audio.sourceStart, 1); assert.equal(placed.video.linkGroupId, placed.audio.linkGroupId); assert.equal(placed.groupId, placed.video.linkGroupId);
let moved = moveLinkedGroup(project, placed.video.id, 3); assert.deepEqual(moved.items.map(entry => entry.item.start), [3, 3]); assert.equal(moved.delta, 3); let trimmed = trimLinkedGroup(project, placed.groupId, { newStart: 4, newEnd: 6 }); assert.deepEqual(trimmed.items.map(entry => [entry.item.start, entry.item.duration, entry.item.sourceStart]), [[4, 2, 2], [4, 2, 2]]); assert.equal(validateProject(project).valid, true);
let unlinked = unlinkTimelineItems(project, placed.video.id); assert.equal(unlinked.itemIds.length, 2); assert.equal(placed.video.linkGroupId, undefined); assert.throws(() => moveLinkedGroup(project, placed.video.id, 1), /not found/); const relinked = linkTimelineItems(project, [placed.video.id, placed.audio.id], "manual-link"); assert.equal(relinked.groupId, "manual-link");
const timeline = activeTimeline(project); applyTimelineEdit(project, { trackName: "V1", adds: [{ assetId: "still", start: 0, sourceStart: 0, duration: 2, label: "Block" }] }); assert.throws(() => moveLinkedGroup(project, "manual-link", 1), /overlaps/); assert.deepEqual([placed.video.start, placed.audio.start], [4, 4]);
const insertedProject = newProject({ name: "Insert linked", width: 320, height: 180, fps: 30 }); insertedProject.assets.push(...project.assets); applyTimelineEdit(insertedProject, { trackName: "V1", adds: [{ assetId: "still", start: 0, sourceStart: 0, duration: 4 }] }); applyTimelineEdit(insertedProject, { trackName: "A1", adds: [{ assetId: "bed", start: 0, sourceStart: 0, duration: 4 }] }); activeTimeline(insertedProject).captions = { enabled: true, style: {}, cues: [{ start: 3, end: 4, text: "later" }] }; placed = placeLinkedAv(insertedProject, { assetId: "av", videoTrackIdOrName: "V1", audioTrackIdOrName: "A1", mode: "insert", at: 2, sourceStart: 2, duration: 2 }); assert.deepEqual(activeTimeline(insertedProject).tracks.find(track => track.name === "V1").items.map(item => [item.start, item.duration]), [[0, 2], [2, 2], [4, 2]]); assert.deepEqual(activeTimeline(insertedProject).tracks.find(track => track.name === "A1").items.map(item => [item.start, item.duration]), [[0, 2], [2, 2], [4, 2]]); assert.equal(activeTimeline(insertedProject).captions.cues[0].start, 5);
assert.throws(() => placeLinkedAv(project, { assetId: "still", videoTrackIdOrName: "V1", audioTrackIdOrName: "A1" }), /requires a video asset with audio/); activeTimeline(insertedProject).tracks.find(track => track.name === "A1").locked = true; assert.throws(() => placeLinkedAv(insertedProject, { assetId: "av", videoTrackIdOrName: "V1", audioTrackIdOrName: "A1", mode: "append" }), /locked/);
console.log(JSON.stringify({ ok: true, groupId: placed.groupId, linkedModes: ["append", "insert", "overwrite"], movedAndTrimmed: true }, null, 2));
