import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import puppeteer from "puppeteer-core";

const root = mkdtempSync(join(tmpdir(), "mycut-proxy-mcp-")), projectPath = join(root, "proxy.mycut.json"), source = join(root, "source.mp4"); const made = spawnSync("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc2=s=1280x720:r=24:d=2", "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", source], { encoding: "utf8" }); assert.equal(made.status, 0, made.stderr);
const client = new Client({ name: "proxy-mcp", version: "1" }), transport = new StdioClientTransport({ command: process.execPath, args: [resolve("scripts/server.mjs")], cwd: resolve(".") }); await client.connect(transport); const call = async (name, args) => { const response = await client.callTool({ name, arguments: args }); if (response.isError) throw new Error(response.content[0].text); return JSON.parse(response.content[0].text); };
await call("create_project", { projectPath, name: "Proxy MCP", width: 1280, height: 720, fps: 24 }); const asset = (await call("import_assets", { projectPath, paths: [source] })).imported[0]; await call("place_asset_on_timeline", { projectPath, assetId: asset.id, trackIdOrName: "V1", mode: "append", sourceStart: 0, sourceEnd: 2 });
const generated = await call("generate_video_proxy", { projectPath, assetId: asset.id, profile: "540p", quality: 26, includeAudio: false }); assert.deepEqual([generated.proxy.media.width, generated.proxy.media.height], [960, 540]); assert.equal((await call("read_asset_proxy", { projectPath, assetId: asset.id })).status, "ready"); assert.equal((await call("scan_proxy_status", { projectPath })).ready, 1);
const review = await call("open_review_session", { projectPath }), rootUrl = new URL(review.url).origin, proxyResponse = await fetch(`${rootUrl}/media?token=${review.token}&assetId=${asset.id}&proxy=1`), originalResponse = await fetch(`${rootUrl}/media?token=${review.token}&assetId=${asset.id}`); assert.equal(proxyResponse.status, 200); assert.equal(proxyResponse.headers.get("x-mycut-media"), "proxy"); assert.equal(originalResponse.headers.get("x-mycut-media"), "original"); assert.ok((await proxyResponse.arrayBuffer()).byteLength > 1000); assert.ok((await originalResponse.arrayBuffer()).byteLength > 1000);
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true, args: ["--no-sandbox"] }), page = await browser.newPage(), errors = []; page.on("pageerror", error => errors.push(error.message)); await page.goto(review.url, { waitUntil: "networkidle0" }); await page.click(`[data-asset="${asset.id}"]`); await page.waitForSelector("#generateProxy"); assert.match(await page.$eval("#panel", element => element.textContent), /代理 540p/); assert.equal(await page.$eval("#sourceMedia", element => new URL(element.src).searchParams.get("proxy")), "1"); assert.equal(errors.length, 0); await browser.close(); await call("close_review_session", { token: review.token });
const rendered = await call("render_project", { projectPath, outputPath: join(root, "final.mp4"), resolution: "original", burnCaptions: false }); const stream = rendered.probe.streams.find((entry) => entry.codec_type === "video"); assert.deepEqual([stream.width, stream.height], [1280, 720]); const detached = await call("detach_video_proxy", { projectPath, assetId: asset.id, deleteFile: true }); assert.equal(detached.deleted, true); assert.equal((await call("read_asset_proxy", { projectPath, assetId: asset.id })).status, "none"); await client.close();
console.log(JSON.stringify({ ok: true, proxy: [generated.proxy.media.width, generated.proxy.media.height], final: [stream.width, stream.height], headers: { proxy: "proxy", original: "original" }, browserErrors: errors }, null, 2));
