import assert from "node:assert/strict";
import { mkdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { activeTimeline, newProject, validateProject } from "../scripts/project-store.mjs";
import { applySilenceCut, analyzeAssetSilence, keepRangesFromSilence, parseSilenceDetect } from "../scripts/silence-edit-engine.mjs";
import { probeOutput, renderProject } from "../scripts/media-engine.mjs";

const root = resolve(process.argv[2] || "/tmp/mycut-silence-editing"); rmSync(root, { recursive: true, force: true }); mkdirSync(root, { recursive: true }); const source = `${root}/pauses.mp4`, output = `${root}/cut.mp4`, run = (args) => { const result = spawnSync("ffmpeg", args, { encoding: "utf8" }); if (result.status !== 0) throw new Error(result.stderr); }; run(["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=blue:s=320x180:r=24:d=5", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=1", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono:d=1", "-f", "lavfi", "-i", "sine=frequency=660:sample_rate=48000:duration=1", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono:d=1", "-f", "lavfi", "-i", "sine=frequency=880:sample_rate=48000:duration=1", "-filter_complex", "[1:a][2:a][3:a][4:a][5:a]concat=n=5:v=0:a=1[a]", "-map", "0:v", "-map", "[a]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", source]);
assert.deepEqual(parseSilenceDetect("silence_start: 1\nsilence_end: 2\nsilence_start: 4", 5).map(range => [range.start, range.end]), [[1, 2], [4, 5]]); assert.deepEqual(keepRangesFromSilence([{ start: 1, end: 2 }, { start: 3, end: 4 }], 5, { padding: .1 }).map(range => [range.start, range.end]), [[0, 1.1], [1.9, 3.1], [3.9, 5]]);
const transcript = { cues: [{ start: .1, end: .8, text: "one", words: [{ start: .1, end: .8, text: "one" }] }, { start: 2.1, end: 2.8, text: "two", words: [{ start: 2.1, end: 2.8, text: "two" }] }, { start: 4.1, end: 4.8, text: "three", words: [{ start: 4.1, end: 4.8, text: "three" }] }] }, asset = { id: "camera", path: source, name: "Camera", type: "video", duration: 5, width: 320, height: 180, hasAudio: true, transcript }, analysis = analyzeAssetSilence(asset, { thresholdDb: -40, minSilence: .5, padding: .1, minKeep: .1 }); assert.equal(analysis.silences.length, 2); assert.ok(Math.abs(analysis.silences[0].start - 1) < .1); assert.ok(Math.abs(analysis.silences[1].start - 3) < .1); assert.ok(analysis.removedDuration > 1.5 && analysis.removedDuration < 1.8);
const project = newProject({ name: "Silence cut", width: 320, height: 180, fps: 24 }); project.assets.push(asset); const applied = applySilenceCut(project, { assetId: asset.id, keepRanges: analysis.keepRanges, videoTrackName: "V1", audioTrackName: "A1", includeVideo: true, includeAudio: true }); assert.equal(applied.segments.length, 3); assert.ok(applied.segments.every(segment => segment.groupId)); assert.deepEqual(activeTimeline(project).tracks.find(track => track.name === "V1").items.map(item => item.linkGroupId), activeTimeline(project).tracks.find(track => track.name === "A1").items.map(item => item.linkGroupId)); assert.deepEqual(applied.captions.map(cue => cue.text), ["one", "two", "three"]); assert.equal(validateProject(project).valid, true); renderProject(project, output, { burnCaptions: true }); const probe = probeOutput(output); assert.ok(Math.abs(Number(probe.format.duration) - analysis.keptDuration) < .1);
assert.throws(() => analyzeAssetSilence(asset, { thresholdDb: -100 }), /threshold/); assert.throws(() => applySilenceCut(project, { assetId: asset.id, keepRanges: [{ start: 2, end: 3 }, { start: 1, end: 2 }] }), /overlapping/); activeTimeline(project).tracks.find(track => track.name === "A1").locked = true; assert.throws(() => applySilenceCut(project, { assetId: asset.id, keepRanges: analysis.keepRanges }), /locked/);
console.log(JSON.stringify({ ok: true, silences: analysis.silences, keepRanges: analysis.keepRanges, removedDuration: analysis.removedDuration, renderedDuration: Number(probe.format.duration), output }, null, 2));
