import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { applyTimelineEdit, newProject, validateProject } from "../scripts/project-store.mjs";
import { renderProject } from "../scripts/media-engine.mjs";
import { analyzeSaliencyFrames, analyzeSmartReframe, applySmartReframe, clearSmartReframe, validateReframe } from "../scripts/smart-reframe-engine.mjs";
import { splitTimelineItem } from "../scripts/timeline-operations-engine.mjs";

const root = mkdtempSync(join(tmpdir(), "mycut-reframe-")), source = join(root, "moving.mp4"), output = join(root, "vertical.mp4"); const made = spawnSync("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=black:s=640x360:r=24:d=3", "-f", "lavfi", "-i", "color=c=red:s=100x160:r=24:d=3", "-filter_complex", "[0:v][1:v]overlay=x='40+150*t':y=100:shortest=1", "-c:v", "libx264", "-pix_fmt", "yuv420p", source], { encoding: "utf8" }); assert.equal(made.status, 0, made.stderr);
const project = newProject({ name: "Smart reframe", width: 360, height: 640, fps: 24 }), asset = { id: "moving", name: "Moving subject", path: source, type: "video", duration: 3, width: 640, height: 360, fps: "24/1", hasAudio: false }; project.assets.push(asset); const edited = applyTimelineEdit(project, { trackName: "V1", adds: [{ assetId: asset.id, start: 0, sourceStart: 0, duration: 3, label: "Follow subject" }] }), item = edited.track.items[0];
const plan = analyzeSmartReframe(asset, { targetWidth: 360, targetHeight: 640, sampleFps: 6, analysisWidth: 160, smoothing: .45, keyframeInterval: .33 }); assert.equal(plan.nonMutating, true); assert.equal(item.reframe, undefined); assert.ok(plan.keyframes.length >= 7); assert.ok(plan.keyframes.at(-1).focusX - plan.keyframes[1].focusX > .35, JSON.stringify(plan.keyframes)); assert.ok(plan.averageConfidence > .01);
const applied = applySmartReframe(project, { itemId: item.id, plan }); assert.equal(applied.validation.valid, true); assert.equal(item.reframe.detector, "local-saliency-motion-v1"); assert.equal(validateProject(project).valid, true); renderProject(project, output, { crf: 18 });
const sample = (time) => { const result = spawnSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-ss", String(time), "-i", output, "-vf", "crop=80:160:(iw-80)/2:(ih-160)/2,scale=1:1", "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb24", "pipe:1"], { encoding: null }); assert.equal(result.status, 0, result.stderr?.toString()); return [...result.stdout]; }, early = sample(.5), late = sample(2.5); for (const pixel of [early, late]) assert.ok(pixel[0] > pixel[1] * 2 && pixel[0] > pixel[2] * 2, `subject not centered: ${pixel}`);
const split = splitTimelineItem(project, item.id, 1.5); assert.equal(split.left.reframe.keyframes[0].time, 0); assert.equal(split.left.reframe.keyframes.at(-1).time, 1.5); assert.equal(split.right.reframe.keyframes[0].time, 0); assert.equal(split.right.reframe.keyframes.at(-1).time, 1.5); assert.equal(clearSmartReframe(project, item.id).removed, true); assert.equal(split.left.reframe, undefined); assert.equal(validateReframe({ targetWidth: 360, targetHeight: 640, keyframes: [{ time: 4, focusX: .5, focusY: .5 }] }, 3).valid, false); assert.throws(() => analyzeSaliencyFrames(Buffer.alloc(4), { width: 3, height: 3, fps: 2 }), /Invalid/);
console.log(JSON.stringify({ ok: true, detector: plan.detector, frames: plan.framesAnalyzed, keyframes: plan.keyframes, confidence: plan.averageConfidence, centerPixels: { early, late }, output }, null, 2));
