import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import puppeteer from "puppeteer-core";

const root = mkdtempSync(join(tmpdir(), "mycut-subtitle-mcp-")), projectPath = join(root, "subtitle.mycut.json"), input = join(root, "input.vtt"), video = join(root, "background.mp4"); writeFileSync(input, `WEBVTT\n\nintro\n00:00:00.200 --> 00:00:01.300\nBuild locally\n\nsecond\n00:00:01.500 --> 00:00:02.700\nEdit with AI\n`); const made = spawnSync("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=0x162033:s=480x270:r=24:d=3", "-c:v", "libx264", "-pix_fmt", "yuv420p", video], { encoding: "utf8" }); assert.equal(made.status, 0, made.stderr);
const client = new Client({ name: "subtitle-mcp", version: "1" }), transport = new StdioClientTransport({ command: process.execPath, args: [resolve("scripts/server.mjs")], cwd: resolve(".") }); await client.connect(transport); const call = async (name, args) => { const response = await client.callTool({ name, arguments: args }); if (response.isError) throw new Error(response.content[0].text); return JSON.parse(response.content[0].text); };
await call("create_project", { projectPath, name: "Subtitle MCP", width: 480, height: 270, fps: 24 }); const asset = (await call("import_assets", { projectPath, paths: [video] })).imported[0]; await call("place_asset_on_timeline", { projectPath, assetId: asset.id, trackIdOrName: "V1", mode: "append", sourceStart: 0, sourceEnd: 3 });
const imported = await call("import_subtitles", { projectPath, inputPath: input, format: "vtt", offset: 0, enabled: true, preserveStyle: true }); assert.equal(imported.cues.length, 2); assert.equal(imported.cues[0].id, "intro");
const translated = await call("set_caption_translations", { projectPath, language: "zh-CN", translations: [{ id: "intro", text: "本地构建" }, { id: "second", text: "使用 AI 剪辑" }] }); assert.equal(translated.cues[1].translation, "使用 AI 剪辑"); await call("update_caption_style", { projectPath, style: { template: "bold-box", fontSize: 38, secondaryFontSize: 24, secondaryColor: "#7dd3fc", bilingual: true, position: "bottom" } });
for (const format of ["srt", "vtt", "ass"]) { const outputPath = join(root, `bilingual.${format}`), result = await call("export_subtitles", { projectPath, outputPath, format, variant: "bilingual" }); assert.equal(result.cues, 2); assert.match(readFileSync(outputPath, "utf8"), /本地构建/); }
const rendered = await call("render_project", { projectPath, outputPath: join(root, "burned.mp4"), burnCaptions: true, codec: "h264", crf: 18 }); assert.equal(rendered.captionsBurned, true); assert.ok(Number(rendered.probe.format.duration) >= 2.9);
const review = await call("open_review_session", { projectPath, previewPath: join(root, "burned.mp4") }), browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true, args: ["--no-sandbox"] }), page = await browser.newPage(), errors = []; page.on("pageerror", error => errors.push(error.message)); await page.goto(review.url, { waitUntil: "networkidle0" }); await page.click('[data-tab="captions"]'); await page.waitForSelector("#importSubtitle"); assert.equal(await page.$$eval("[data-translation]", elements => elements.length), 2); assert.match(await page.$eval("#panel", element => element.textContent), /字幕互操作/); assert.equal(errors.length, 0); await browser.close(); await call("close_review_session", { token: review.token }); await client.close();
console.log(JSON.stringify({ ok: true, root, cues: translated.cues.length, formats: ["srt", "vtt", "ass"], rendered: rendered.outputPath, browserErrors: errors }, null, 2));
