import assert from "node:assert/strict";
import { mkdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { activeTimeline, applyTimelineEdit, newProject, validateProject } from "../scripts/project-store.mjs";
import { ASPECT_PRESETS, projectForExportFormat, setTimelineFormat } from "../scripts/timeline-management-engine.mjs";
import { probeOutput, renderProject } from "../scripts/media-engine.mjs";

const root = resolve(process.argv[2] || "/tmp/mycut-timeline-format"); rmSync(root, { recursive: true, force: true }); mkdirSync(root, { recursive: true }); const source = `${root}/source.mp4`;
const run = (command, args) => { const result = spawnSync(command, args, { encoding: "utf8" }); if (result.status !== 0) throw new Error(result.stderr); return result.stdout; };
run("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc2=s=320x180:r=30:d=1", "-c:v", "libx264", "-pix_fmt", "yuv420p", source]);
const project = newProject({ name: "Format", width: 320, height: 180, fps: 30 }); project.assets.push({ id: "source", path: source, name: "source", type: "video", duration: 1, width: 320, height: 180, hasAudio: false }); applyTimelineEdit(project, { trackName: "V1", adds: [{ assetId: "source", start: 0, sourceStart: 0, duration: 1, transform: { x: 32, y: 18, width: 160, height: 90, keyframes: [{ time: 0, x: 32, y: 18 }, { time: 1, x: 64, y: 36 }] }, effects: [{ type: "mask", shape: "rectangle", x: 16, y: 9, width: 128, height: 72, feather: 4, invert: false }] }] }); const timeline = activeTimeline(project); timeline.captions = { enabled: true, cues: [{ start: 0, end: 1, text: "Resize" }], style: { fontSize: 20, margin: 18, maxWidth: 240, outlineWidth: 2 } };
assert.deepEqual(Object.keys(ASPECT_PRESETS), ["16:9", "9:16", "1:1", "4:3", "3:4"]); let changed = setTimelineFormat(project, timeline.id, { width: 640, height: 360, fps: 30, layoutMode: "scale" }); let item = activeTimeline(project).tracks[0].items[0]; assert.deepEqual([item.transform.x, item.transform.y, item.transform.width, item.transform.height], [64, 36, 320, 180]); assert.deepEqual([item.transform.keyframes[1].x, item.transform.keyframes[1].y], [128, 72]); assert.deepEqual([item.effects[0].x, item.effects[0].y, item.effects[0].width, item.effects[0].height, item.effects[0].feather], [32, 18, 256, 144, 8]); assert.equal(activeTimeline(project).captions.style.fontSize, 40); assert.equal(changed.scaling.uniform, 2);
changed = setTimelineFormat(project, timeline.id, { preset: "9:16", fps: 60, layoutMode: "scale" }); assert.equal(changed.timeline.width, 1080); assert.equal(changed.timeline.height, 1920); assert.equal(changed.timeline.fps, 60); assert.equal(validateProject(project).valid, true);
const originalSnapshot = JSON.stringify(project), exported = projectForExportFormat(project, { resolution: "480p", frameRate: 24 }); assert.deepEqual(exported.format, { resolution: "480p", width: 480, height: 854, fps: 24 }); assert.equal(JSON.stringify(project), originalSnapshot); assert.equal(activeTimeline(exported.project).width, 480); assert.equal(activeTimeline(exported.project).height, 854);
const output = `${root}/vertical-480p-24fps.mp4`; renderProject(exported.project, output, { burnCaptions: true }); const probe = probeOutput(output), stream = probe.streams.find((entry) => entry.codec_type === "video"); assert.deepEqual([stream.width, stream.height, stream.r_frame_rate], [480, 854, "24/1"]); assert.ok(Math.abs(Number(probe.format.duration) - 1) < 0.06);
const preserved = structuredClone(project), beforeX = activeTimeline(preserved).tracks[0].items[0].transform.x; setTimelineFormat(preserved, null, { preset: "1:1", layoutMode: "preserve" }); assert.equal(activeTimeline(preserved).tracks[0].items[0].transform.x, beforeX); assert.throws(() => projectForExportFormat(project, { resolution: "4k", frameRate: 30 }), /Unsupported/); assert.throws(() => projectForExportFormat(project, { resolution: "original", frameRate: 120 }), /24-60/);
console.log(JSON.stringify({ ok: true, persistent: { width: activeTimeline(project).width, height: activeTimeline(project).height, fps: activeTimeline(project).fps }, exportFormat: exported.format, output, probe: stream }, null, 2));
