import assert from "node:assert/strict";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { newProject, validateProject } from "../scripts/project-store.mjs";
import { listVideoTypes, selectVideoType } from "../scripts/video-type-engine.mjs";
import { analyzeVlogCoverage, analyzeVlogRelease, analyzeVlogRhythm, analyzeVlogWorkflow, applyVlogBroll, applyVlogEdit, applyVlogFinishing, applyVlogReleaseFixes, applyVlogRhythm, applyVlogSound, planVlogBroll, planVlogEdit, planVlogFinishing, planVlogRhythm, planVlogSound, renderVlogTitleCards } from "../scripts/vlog-engine.mjs";

const project = newProject({ name: "My Vlog", width: 1920, height: 1080, fps: 30 });
assert.equal(listVideoTypes().filter((entry) => entry.available).length, 7);
for (const type of listVideoTypes().filter((entry) => entry.id !== "vlog")) { const typed = newProject({ name:type.label,width:1920,height:1080,fps:30 }); selectVideoType(typed,type.id,{ format:"landscape",objective:`Create ${type.label}` }); assert.equal(typed.videoType.id,type.id); assert.ok(typed.timelines[0].tracks.length >= 5); assert.equal(validateProject(typed).valid,true); }
selectVideoType(project, "vlog", { format: "vertical", style: "travel", pace: "energetic", targetDuration: 20, objective: "A day on Vancouver Island", narration: "mixed", musicMood: "upbeat" });
assert.equal(project.videoType.id, "vlog"); assert.deepEqual([project.timelines[0].width, project.timelines[0].height], [1080, 1920]); assert.ok(project.timelines[0].tracks.some((track) => track.name === "V1 · Story")); assert.ok(project.bins.some((entry) => entry.name === "Travel"));
project.assets.push(
  { id: "arrival", name: "Arrival surprise.mov", path: "/tmp/arrival.mov", type: "video", duration: 12, annotation: { tags: ["arrival", "hook", "travel"], quality: .9, motion: .8 } },
  { id: "walk", name: "Walking through town.mov", path: "/tmp/walk.mov", type: "video", duration: 16, annotation: { tags: ["walk", "people", "journey"], quality: .8, motion: .75 } },
  { id: "food", name: "Food details.mov", path: "/tmp/food.mov", type: "video", duration: 10, annotation: { tags: ["food", "detail"], quality: .85, motion: .4 } },
  { id: "sunset", name: "Sunset hero.mov", path: "/tmp/sunset.mov", type: "video", duration: 11, annotation: { tags: ["sunset", "hero", "outro"], quality: .95, motion: .25 } },
  { id: "coding", name: "Laptop coding.mov", path: "/tmp/coding.mov", type: "video", duration: 9, hasAudio: true, annotation: { tags: ["keyboard", "AI", "programming"], quality: .9, motion: .4 } },
  { id: "wedding", name: "Wedding ceremony.mov", path: "/tmp/wedding.mov", type: "video", duration: 13, annotation: { tags: ["bride", "groom", "ring"], quality: .92, motion: .5 } },
  { id: "music", name: "Warm upbeat music.wav", path: "/tmp/music.wav", type: "audio", duration: 8, annotation: { tags: ["music", "upbeat"] } },
  { id: "whoosh", name: "Transition whoosh SFX.wav", path: "/tmp/whoosh.wav", type: "audio", duration: .8, annotation: { tags: ["sfx", "transition"] } },
);
const coverage = analyzeVlogCoverage(project); assert.equal(coverage.sections.length, 5); assert.equal(coverage.readyToPlan, true); assert.equal(coverage.summary.ready + coverage.summary.thin + coverage.summary.missing, 5); assert.ok(coverage.sections.find((entry) => entry.id === "hook").exactMatches >= 1); assert.ok(coverage.suggestions.every((entry) => entry.text.length > 8));
const plan = planVlogEdit(project); assert.equal(plan.type, "vlog"); assert.equal(plan.duration, 20); assert.ok(plan.shots.length >= 9); assert.deepEqual(plan.sections.map((entry) => entry.id), ["hook","setup","journey","payoff","outro"]); assert.equal(plan.shots[0].section, "hook"); assert.equal(plan.shots.at(-1).section, "outro");
const applied = applyVlogEdit(project, plan); assert.equal(applied.items.length, plan.shots.length); assert.equal(validateProject(project).valid, true); assert.equal(applied.items[0].start, 0); assert.equal(Number((applied.items.at(-1).start + applied.items.at(-1).duration).toFixed(3)), 20);
project.timelines[0].captions = { enabled: true, style: {}, cues: [{ start: 1, end: 4, text: "晚上回家学 AI，写代码" }, { start: 5, end: 9, text: "周末还得接拍摄的单，婚礼什么都拍" }, { start: 10, end: 13, text: "这句话没有对应素材" }] };
const broll = planVlogBroll(project); assert.equal(broll.type, "vlog-broll"); assert.equal(broll.cues, 3); assert.equal(broll.shots.length, 2); assert.equal(broll.gaps.length, 1); assert.equal(broll.shots[0].assetId, "coding"); assert.equal(broll.shots[1].assetId, "wedding"); assert.ok(broll.shots.every((shot) => shot.reason.startsWith("matched narration"))); const appliedBroll = applyVlogBroll(project, broll); assert.equal(appliedBroll.items.length, 2); assert.equal(appliedBroll.trackName, "V2 · Cutaways"); assert.equal(validateProject(project).valid, true);
const storyItems = project.timelines[0].tracks.find((track) => track.name === "V1 · Story").items; storyItems.at(-1).duration = 6; storyItems[1].assetId = storyItems[0].assetId; const rhythmAudit = analyzeVlogRhythm(project, { maxShotSeconds: 3, maxTalkingHeadSeconds: 4 }); assert.ok(rhythmAudit.counts.longShots >= 1); assert.ok(rhythmAudit.counts.repeatedShots >= 1); assert.ok(rhythmAudit.score < 100); const rhythmPlan = planVlogRhythm(project, { maxShotSeconds: 3, maxTalkingHeadSeconds: 4 }); assert.equal(rhythmPlan.type, "vlog-rhythm-plan"); assert.ok(rhythmPlan.cutawayUpdates.length >= 2); assert.equal(rhythmPlan.summary.duckingConfigured, true); const rhythmApplied = applyVlogRhythm(project, rhythmPlan); assert.equal(rhythmApplied.validation.valid, true); assert.equal(project.timelines[0].tracks.find((track) => track.name === "A1 · Voice & Natural Sound").role, "anchor"); assert.equal(project.timelines[0].tracks.find((track) => track.name === "A2 · Music").role, "follower"); assert.equal(project.timelines[0].tracks.find((track) => track.name === "V2 · Cutaways").items[0].transitionIn.type, "cross-dissolve");
const soundPlan = planVlogSound(project); assert.equal(soundPlan.type, "vlog-sound-plan"); assert.ok(soundPlan.musicItems.length >= 4); assert.ok(soundPlan.ambienceItems.length >= 1); assert.equal(soundPlan.sfxItems.length, 1); assert.equal(soundPlan.warnings.length, 0); const soundApplied = applyVlogSound(project, soundPlan); assert.equal(soundApplied.validation.valid, true); assert.ok(soundApplied.musicItems >= 4); assert.ok(soundApplied.soundItems >= 2); assert.equal(project.timelines[0].tracks.find((track) => track.name === "A2 · Music").role, "follower"); assert.ok(project.timelines[0].tracks.some((track) => track.name === "A4 · Natural Sound"));
const finishingPlan = planVlogFinishing(project, { cta: "明天继续" }); assert.equal(finishingPlan.type, "vlog-finishing-plan"); assert.ok(finishingPlan.titleCards.length >= 2); assert.equal(finishingPlan.titleCards[0].kind, "title"); assert.equal(finishingPlan.titleCards.at(-1).title, "明天继续"); assert.equal(finishingPlan.exportPreset.aspect, "9:16"); assert.ok(finishingPlan.safeArea.bottom > finishingPlan.safeArea.top); const finishingApplied = applyVlogFinishing(project, finishingPlan); assert.equal(finishingApplied.validation.valid, true); assert.equal(finishingApplied.pendingTitleCards.length, finishingPlan.titleCards.length); assert.equal(project.timelines[0].captions.style.template, "bold-box"); assert.equal(project.timelines[0].markers.filter((marker) => marker.finishingDirector).length, finishingPlan.markers.length); assert.equal(project.timelines[0].exportPreset.burnCaptions, true);
const titleRoot = "/tmp/cutpilot-vlog-title-render"; rmSync(titleRoot, { recursive: true, force: true }); mkdirSync(titleRoot, { recursive: true }); const renderedTitles = renderVlogTitleCards(project, `${titleRoot}/project.cutpilot.json`); assert.equal(renderedTitles.validation.valid, true); assert.equal(renderedTitles.rendered.filter((entry) => !entry.skipped).length, finishingPlan.titleCards.length); assert.ok(renderedTitles.rendered.every((entry) => entry.skipped || (existsSync(entry.sourcePath) && existsSync(entry.outputPath)))); const titleTrack = project.timelines[0].tracks.find((track) => track.name === "V3 · Titles"); assert.equal(titleTrack.items.length, finishingPlan.titleCards.length); assert.ok(titleTrack.items.every((item) => item.fadeIn > 0 && item.fadeOut > 0)); assert.ok(project.assets.filter((asset) => asset.finishingTitleCard).every((asset) => asset.motionGraphic.engine === "svg"));
const releaseTimeline = project.timelines[0]; releaseTimeline.tracks.find((track) => track.name === "A2 · Music").role = "mix"; delete releaseTimeline.settings.safeArea; delete releaseTimeline.exportPreset; releaseTimeline.captions.enabled = false; const release = analyzeVlogRelease(project); assert.equal(release.type, "vlog-release-preflight"); assert.equal(release.ready, false); assert.ok(release.blockers.some((entry) => entry.kind === "offline-assets")); assert.ok(release.safeFixes.some((entry) => entry.kind === "music-follower")); assert.ok(release.safeFixes.some((entry) => entry.kind === "safe-area")); assert.ok(release.safeFixes.some((entry) => entry.kind === "export-preset")); assert.ok(release.safeFixes.some((entry) => entry.kind === "enable-captions")); const fixedRelease = applyVlogReleaseFixes(project, release); assert.equal(fixedRelease.applied.length, 4); assert.equal(releaseTimeline.tracks.find((track) => track.name === "A2 · Music").role, "follower"); assert.equal(releaseTimeline.captions.enabled, true); assert.ok(releaseTimeline.settings.safeArea); assert.ok(releaseTimeline.exportPreset); assert.equal(fixedRelease.remaining.ready, false); assert.ok(fixedRelease.remaining.blockers.some((entry) => entry.kind === "offline-assets"));
const workflow = analyzeVlogWorkflow(project); assert.equal(workflow.type, "vlog-workflow-status"); assert.equal(workflow.total, 10); assert.equal(workflow.readyToExport, false); assert.equal(workflow.stages.find((entry) => entry.id === "story").complete, true); assert.equal(workflow.stages.find((entry) => entry.id === "titles").complete, true); assert.equal(workflow.stages.find((entry) => entry.id === "media").complete, false); assert.equal(workflow.stages.find((entry) => entry.id === "release").complete, false); assert.equal(workflow.nextAction.stage, "media"); assert.equal(workflow.nextAction.tool, "relink_missing_from_folder");
console.log(JSON.stringify({ videoType: project.videoType, coverage: coverage.summary, sections: plan.sections, shots: plan.shots.length, assetsUsed: plan.assetsUsed, duration: plan.duration, broll: { matched: broll.matchedCues, gaps: broll.gaps.length, assets: broll.shots.map((shot) => shot.assetId) }, rhythm: { score: rhythmAudit.score, issues: rhythmAudit.counts, safeChanges: rhythmPlan.summary.safeChanges } }, null, 2));
