import { randomUUID } from "node:crypto";
import { activeTimeline, validateProject } from "./project-store.mjs";

const verify = (project) => { const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return validation; };
const requireTrack = (timeline, trackIdOrName) => { const track = timeline.tracks.find((entry) => entry.id === trackIdOrName || entry.name === trackIdOrName); if (!track) throw new Error(`Track not found: ${trackIdOrName}`); return track; };
const defaultName = (timeline, type) => { const prefix = type === "audio" ? "A" : "V", used = new Set(timeline.tracks.filter((track) => track.type === type).map((track) => track.name)); let index = 1; while (used.has(`${prefix}${index}`)) index++; return `${prefix}${index}`; };
const baseTrack = (type, name) => type === "audio" ? { id: randomUUID(), name, type, role: "mix", locked: false, muted: false, volumeDb: 0, denoise: false, normalizeLufs: null, items: [] } : { id: randomUUID(), name, type, locked: false, muted: false, opacity: 1, items: [] };
const reorderByType = (timeline, track, position) => { const same = timeline.tracks.filter((entry) => entry.type === track.type && entry !== track), index = Math.max(0, Math.min(same.length, Number(position))); same.splice(index, 0, track); const videos = track.type === "video" ? same : timeline.tracks.filter((entry) => entry.type === "video"), audios = track.type === "audio" ? same : timeline.tracks.filter((entry) => entry.type === "audio"); timeline.tracks = [...videos, ...audios]; };

export function createTrack(project, { type, name, position } = {}) { if (!['video','audio'].includes(type)) throw new Error("Track type must be video or audio"); const timeline = activeTimeline(project), clean = String(name || defaultName(timeline, type)).trim(); if (!clean) throw new Error("Track name is required"); if (timeline.tracks.some((track) => track.name === clean)) throw new Error(`Track name already exists: ${clean}`); const track = baseTrack(type, clean); timeline.tracks.push(track); reorderByType(timeline, track, position ?? timeline.tracks.filter((entry) => entry.type === type).length - 1); project.history.push({ at: new Date().toISOString(), action: "create_track", trackId: track.id, type, name: clean }); return { track, validation: verify(project) }; }
export function renameTrack(project, trackIdOrName, name) { const timeline = activeTimeline(project), track = requireTrack(timeline, trackIdOrName), clean = String(name || "").trim(); if (!clean) throw new Error("Track name is required"); if (timeline.tracks.some((entry) => entry !== track && entry.name === clean)) throw new Error(`Track name already exists: ${clean}`); const previousName = track.name; track.name = clean; project.history.push({ at: new Date().toISOString(), action: "rename_track", trackId: track.id, previousName, name: clean }); return { track, validation: verify(project) }; }
export function reorderTrack(project, trackIdOrName, position) { const timeline = activeTimeline(project), track = requireTrack(timeline, trackIdOrName); if (!Number.isInteger(position) || position < 0) throw new Error("Track position must be a non-negative integer"); reorderByType(timeline, track, position); project.history.push({ at: new Date().toISOString(), action: "reorder_track", trackId: track.id, position }); return { track, tracks: timeline.tracks.map((entry) => entry.name), validation: verify(project) }; }
const overlaps = (a, b) => a.start < b.start + b.duration - 0.0001 && b.start < a.start + a.duration - 0.0001;
export function deleteTrack(project, trackIdOrName, { deleteItems = false, destinationTrackId } = {}) { const timeline = activeTimeline(project), track = requireTrack(timeline, trackIdOrName); if (timeline.tracks.filter((entry) => entry.type === track.type).length <= 1) throw new Error(`Cannot delete the last ${track.type} track`); if (track.items.length && destinationTrackId) { const destination = requireTrack(timeline, destinationTrackId); if (destination === track || destination.type !== track.type) throw new Error("Destination track must be a different track of the same type"); if (destination.locked) throw new Error(`Track ${destination.name} is locked`); for (const item of track.items) if (destination.items.some((candidate) => overlaps(candidate, item))) throw new Error(`Destination ${destination.name} overlaps item ${item.id}`); destination.items.push(...track.items); destination.items.sort((a, b) => a.start - b.start); } else if (track.items.length && !deleteItems) throw new Error("Track contains items; choose deleteItems or destinationTrackId"); timeline.tracks = timeline.tracks.filter((entry) => entry !== track); project.history.push({ at: new Date().toISOString(), action: "delete_track", trackId: track.id, items: track.items.length, destinationTrackId: destinationTrackId || null }); return { deletedTrackId: track.id, validation: verify(project) }; }
export function updateTrack(project, trackIdOrName, changes = {}) { const timeline = activeTimeline(project), track = requireTrack(timeline, trackIdOrName), allowed = track.type === "audio" ? new Set(["locked","muted","role","volumeDb","denoise","normalizeLufs"]) : new Set(["locked","muted","opacity"]); for (const [key, value] of Object.entries(changes)) if (value !== undefined && allowed.has(key)) track[key] = value; project.history.push({ at: new Date().toISOString(), action: "update_track", trackId: track.id, changes }); return { track, validation: verify(project) }; }

export function setSnapping(project, { enabled, toleranceFrames } = {}) { const timeline = activeTimeline(project); timeline.settings ||= {}; timeline.settings.snapping ||= { enabled: true, toleranceFrames: 3 }; if (enabled !== undefined) timeline.settings.snapping.enabled = Boolean(enabled); if (toleranceFrames !== undefined) { if (!Number.isFinite(toleranceFrames) || toleranceFrames < 0 || toleranceFrames > 30) throw new Error("Snap tolerance must be 0-30 frames"); timeline.settings.snapping.toleranceFrames = Number(toleranceFrames); } project.history.push({ at: new Date().toISOString(), action: "set_snapping", snapping: timeline.settings.snapping }); return { snapping: timeline.settings.snapping, validation: verify(project) }; }
export function snapTimelineTime(timeline, time, { excludeItemId, playhead, toleranceFrames } = {}) { const value = Number(time); if (!Number.isFinite(value) || value < 0) throw new Error("Snap time must be non-negative"); const settings = timeline.settings?.snapping || { enabled: true, toleranceFrames: 3 }, tolerance = Number(toleranceFrames ?? settings.toleranceFrames ?? 3) / timeline.fps; if (!settings.enabled) return { input: value, time: value, snapped: false, guide: null, tolerance };
  const guides = [{ time: 0, kind: "timeline-start" }, ...(Number.isFinite(playhead) ? [{ time: Number(playhead), kind: "playhead" }] : []), ...(timeline.markers || []).map((marker) => ({ time: marker.time, kind: "marker", id: marker.id })), ...(timeline.inOut ? [{ time: timeline.inOut.in, kind: "in-point" }, { time: timeline.inOut.out, kind: "out-point" }] : []), ...timeline.tracks.flatMap((track) => track.items.filter((item) => item.id !== excludeItemId).flatMap((item) => [{ time: item.start, kind: "clip-start", itemId: item.id, track: track.name }, { time: item.start + item.duration, kind: "clip-end", itemId: item.id, track: track.name }]))]; const nearest = guides.map((guide) => ({ ...guide, distance: Math.abs(guide.time - value) })).sort((a, b) => a.distance - b.distance || a.time - b.time)[0]; return nearest && nearest.distance <= tolerance + 1e-9 ? { input: value, time: nearest.time, snapped: true, guide: nearest, tolerance } : { input: value, time: value, snapped: false, guide: null, tolerance };
}
export function moveItem(project, itemId, start, options = {}) { const timeline = activeTimeline(project), track = timeline.tracks.find((entry) => entry.items.some((item) => item.id === itemId)); if (!track) throw new Error(`Item not found: ${itemId}`); if (track.locked) throw new Error(`Track ${track.name} is locked`); const item = track.items.find((entry) => entry.id === itemId), snap = options.snap === false ? { input: start, time: Number(start), snapped: false, guide: null } : snapTimelineTime(timeline, start, { ...options, excludeItemId: itemId }); const previousStart = item.start; item.start = snap.time; track.items.sort((a, b) => a.start - b.start); const validation = validateProject(project); if (!validation.valid) { item.start = previousStart; track.items.sort((a, b) => a.start - b.start); throw new Error(validation.errors.join("\n")); } project.history.push({ at: new Date().toISOString(), action: "move_item", itemId, previousStart, start: item.start, snapped: snap.snapped, guide: snap.guide }); return { item, snap, validation };
}
