import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { activeTimeline, validateProject } from "./project-store.mjs";
import { renderSvgMotionGraphic } from "./svg-motion-graphics-engine.mjs";

const sections = [
  { id: "hook", label: "Hook", ratio: .1, terms: ["hook","best","surprise","action","arrival","reveal","精彩","开场","惊喜"] },
  { id: "setup", label: "Setup", ratio: .18, terms: ["intro","start","morning","location","wide","出发","早上","环境","地点"] },
  { id: "journey", label: "Journey", ratio: .47, terms: ["walk","travel","work","process","people","food","detail","走路","旅行","工作","过程","人物","美食","细节"] },
  { id: "payoff", label: "Payoff", ratio: .17, terms: ["result","sunset","hero","reaction","完成","结果","日落","高光","反应"] },
  { id: "outro", label: "Outro", ratio: .08, terms: ["outro","leave","night","reflection","结束","离开","夜晚","总结"] },
];
const paceRanges = { calm: [3.5, 6], balanced: [2, 4], energetic: [1, 2.4] };
const sectionSuggestions = {
  hook: "补一个最有动作、反差或结果感的开场镜头",
  setup: "补一个地点、人物或出发状态的交代镜头",
  journey: "补过程、细节、人物互动或环境变化镜头",
  payoff: "补结果、反应或当天最高光的镜头",
  outro: "补离开、夜晚、回望或总结感镜头",
};
const concepts = [
  ["code","coding","programming","developer","keyboard","computer","laptop","ai","代码","编程","键盘","电脑","人工智能"],
  ["wedding","bride","groom","ceremony","ring","婚礼","新娘","新郎","仪式","戒指"],
  ["photo","camera","shoot","portrait","building","摄影","拍摄","写真","建筑","相机"],
  ["factory","brick","work","shift","砖厂","砖","工厂","上班","工作"],
  ["walk","walking","road","street","走路","走","路上","街道"],
  ["wash","washing","hands","water","洗手","擦干","水"],
  ["food","cook","meal","restaurant","美食","做饭","吃饭","餐厅"],
  ["travel","trip","island","train","flight","旅行","旅游","海岛","火车","飞机"],
];
const text = (candidate) => [candidate.asset.name, candidate.name, candidate.asset.annotation?.description, ...(candidate.asset.annotation?.tags || []), ...(candidate.asset.annotation?.actions || []), ...(candidate.asset.annotation?.locations || []), ...(candidate.tags || []), candidate.annotation].filter(Boolean).join(" ").toLowerCase();

function candidates(project) {
  return project.assets.flatMap((asset) => {
    if (!['video','image'].includes(asset.type)) return [];
    if (asset.subclips?.length) return asset.subclips.map((subclip) => ({ asset, id: subclip.id, name: subclip.name, sourceStart: Number(subclip.sourceStart), duration: Number(subclip.duration), tags: subclip.tags || [], annotation: subclip.annotation || "" }));
    const duration = asset.type === "image" ? 6 : Number(asset.duration || 0); return duration > .2 ? [{ asset, id: asset.id, name: asset.name, sourceStart: 0, duration, tags: [], annotation: "" }] : [];
  });
}

function scoreForSection(entry, section, rhythm = "balanced") {
  const source = text(entry), matches = section.terms.filter((term) => source.includes(term));
  const quality = Number(entry.asset.annotation?.quality ?? .6), motion = Number(entry.asset.annotation?.motion ?? .5);
  return { entry, matches, score: matches.length * 2 + quality + motion * (rhythm === "energetic" ? .6 : .25) };
}

const cueTokens = (value) => [...new Set(String(value || "").toLowerCase().match(/[a-z0-9]+|[\u4e00-\u9fff]{2,}/g) || [])];
function semanticMatches(cue, entry) {
  const cueText = String(cue.text || "").toLowerCase(), source = text(entry), direct = cueTokens(cueText).filter((token) => token.length > 1 && source.includes(token));
  const related = concepts.filter((group) => group.some((term) => cueText.includes(term)) && group.some((term) => source.includes(term))).flatMap((group) => group.filter((term) => source.includes(term)));
  return [...new Set([...direct, ...related])];
}

function narrationCues(project, { cues, transcriptAssetId } = {}) {
  if (Array.isArray(cues) && cues.length) return cues;
  if (transcriptAssetId) {
    const asset = project.assets.find((entry) => entry.id === transcriptAssetId);
    if (!asset?.transcript?.cues?.length) throw new Error(`Transcript not found for asset ${transcriptAssetId}`);
    return asset.transcript.cues;
  }
  return activeTimeline(project).captions?.cues || [];
}

export function planVlogBroll(project, { cues, transcriptAssetId, includeAssetIds = [], excludeAssetIds = [], minCueDuration = .6, maxShotDuration = 4, coverage = .82 } = {}) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before planning narration B-roll");
  const narration = narrationCues(project, { cues, transcriptAssetId }).filter((cue) => Number(cue.end) - Number(cue.start) >= minCueDuration && String(cue.text || "").trim());
  if (!narration.length) throw new Error("Narration B-roll planning requires timeline captions, a transcript asset, or timestamped cues");
  const include = new Set(includeAssetIds), exclude = new Set(excludeAssetIds), pool = candidates(project).filter((entry) => !exclude.has(entry.asset.id) && (!include.size || include.has(entry.asset.id)));
  if (!pool.length) throw new Error("Narration B-roll planning requires at least one video or image asset");
  const used = new Map(), shots = [], gaps = [];
  for (const [index, cue] of narration.entries()) {
    const ranked = pool.map((entry) => { const matches = semanticMatches(cue, entry), quality = Number(entry.asset.annotation?.quality ?? .6), repeats = used.get(entry.asset.id) || 0, adjacent = shots.at(-1)?.assetId === entry.asset.id; return { entry, matches, score: matches.length * 2.5 + quality - repeats * .45 - (adjacent ? 2 : 0) }; }).sort((a,b)=>b.score-a.score||a.entry.name.localeCompare(b.entry.name));
    const best = ranked[0];
    if (!best?.matches.length) { gaps.push({ cueIndex: index, start: Number(cue.start), end: Number(cue.end), text: String(cue.text), reason: "no-semantic-match", suggestion: `为“${String(cue.text).slice(0, 36)}”补拍或标注对应画面` }); continue; }
    const cueDuration = Number(cue.end) - Number(cue.start), duration = Math.min(cueDuration * Math.max(.25, Math.min(1, coverage)), maxShotDuration, best.entry.duration), start = Number(cue.start) + Math.max(0, (cueDuration - duration) / 2), sourceRoom = Math.max(0, best.entry.duration - duration), sourceStart = best.entry.sourceStart + (sourceRoom ? ((index * .41) % 1) * sourceRoom : 0);
    shots.push({ cueIndex: index, cueText: String(cue.text), assetId: best.entry.asset.id, subclipId: best.entry.id === best.entry.asset.id ? null : best.entry.id, start: Number(start.toFixed(3)), sourceStart: Number(sourceStart.toFixed(3)), duration: Number(duration.toFixed(3)), label: best.entry.name, matches: best.matches, score: Number(best.score.toFixed(3)), reason: `matched narration: ${best.matches.join(", ")}` });
    used.set(best.entry.asset.id, (used.get(best.entry.asset.id) || 0) + 1);
  }
  const repeated = [...used.entries()].filter(([, count]) => count > 1).map(([assetId, count]) => ({ assetId, count }));
  return { type: "vlog-broll", transcriptAssetId: transcriptAssetId || null, cues: narration.length, shots, gaps, matchedCues: shots.length, matchRate: Number((shots.length / narration.length).toFixed(3)), repeatedAssets: repeated, nonMutating: true, reviewRequired: true };
}

export function applyVlogBroll(project, plan, { trackName = "V2 · Cutaways", replace = true } = {}) {
  if (plan?.type !== "vlog-broll" || !Array.isArray(plan.shots) || !plan.shots.length) throw new Error("A reviewed Vlog B-roll plan is required");
  const timeline = activeTimeline(project); let track = timeline.tracks.find((entry) => entry.name === trackName);
  if (!track) { track = { id: randomUUID(), name: trackName, type: "video", locked: false, muted: false, opacity: 1, items: [] }; timeline.tracks.push(track); }
  if (track.locked) throw new Error(`Track ${trackName} is locked`); if (replace) track.items = [];
  track.items.push(...plan.shots.map((shot) => ({ id: randomUUID(), assetId: shot.assetId, start: shot.start, sourceStart: shot.sourceStart, duration: shot.duration, volumeDb: 0, opacity: 1, label: `B-roll: ${shot.label}`, narrationCue: { index: shot.cueIndex, text: shot.cueText, matches: shot.matches } })));
  track.items.sort((a,b)=>a.start-b.start); project.history.push({ at: new Date().toISOString(), action: "apply_vlog_broll", shots: plan.shots.length, gaps: plan.gaps.length }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { trackId: track.id, trackName, items: track.items, gaps: plan.gaps, validation };
}

const mergeRanges = (ranges) => ranges.sort((a,b)=>a.start-b.start).reduce((out, range) => { const last = out.at(-1); if (last && range.start <= last.end + .02) last.end = Math.max(last.end, range.end); else out.push({ ...range }); return out; }, []);
export function analyzeVlogRhythm(project, { maxTalkingHeadSeconds, maxShotSeconds, gapWindowSeconds = 6 } = {}) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before analyzing rhythm");
  const timeline = activeTimeline(project), pace = project.videoType.vlog?.pace || "balanced", limits = { calm: [8, 6], balanced: [6, 4], energetic: [4, 2.5] }[pace], maxTalk = Number(maxTalkingHeadSeconds || limits[0]), maxShot = Number(maxShotSeconds || limits[1]);
  const story = timeline.tracks.find((track) => track.name === "V1 · Story") || timeline.tracks.find((track) => track.type === "video"), cutaways = timeline.tracks.find((track) => track.name === "V2 · Cutaways"), captions = timeline.captions?.cues || [];
  const storyItems = [...(story?.items || [])].sort((a,b)=>a.start-b.start), cutawayItems = [...(cutaways?.items || [])].sort((a,b)=>a.start-b.start), end = Math.max(0, ...storyItems.map((item)=>item.start+item.duration), ...captions.map((cue)=>cue.end));
  const longShots = storyItems.filter((item) => item.duration > maxShot).map((item) => ({ itemId: item.id, start: item.start, end: item.start + item.duration, duration: item.duration, label: item.label, suggestion: `在 ${maxShot.toFixed(1)} 秒附近加入动作切点或 B-roll` }));
  const repeatedShots = storyItems.slice(1).flatMap((item, index) => item.assetId === storyItems[index].assetId ? [{ firstItemId: storyItems[index].id, secondItemId: item.id, start: storyItems[index].start, end: item.start + item.duration, assetId: item.assetId, suggestion: "连续使用同一素材，建议换角度或插入细节" }] : []);
  const covered = mergeRanges(cutawayItems.map((item) => ({ start: item.start, end: item.start + item.duration }))), visualGaps = []; let cursor = 0;
  for (const range of covered) { if (range.start - cursor >= gapWindowSeconds) visualGaps.push({ start: cursor, end: range.start, duration: range.start - cursor, suggestion: "连续口播偏长，建议加入环境、动作或细节 B-roll" }); cursor = Math.max(cursor, range.end); }
  if (end - cursor >= gapWindowSeconds) visualGaps.push({ start: cursor, end, duration: end - cursor, suggestion: "连续口播偏长，建议加入环境、动作或细节 B-roll" });
  const talkingHeadRuns = visualGaps.filter((gap) => gap.duration >= maxTalk), audioTracks = timeline.tracks.filter((track) => track.type === "audio"), hasAnchor = audioTracks.some((track) => track.role === "anchor"), hasFollower = audioTracks.some((track) => track.role === "follower");
  const score = Math.max(0, Math.round(100 - longShots.length * 8 - repeatedShots.length * 12 - talkingHeadRuns.length * 10 - (!hasAnchor ? 8 : 0) - (!hasFollower ? 6 : 0)));
  return { type: "vlog-rhythm-audit", pace, duration: Number(end.toFixed(3)), score, limits: { maxTalkingHeadSeconds: maxTalk, maxShotSeconds: maxShot, gapWindowSeconds }, counts: { longShots: longShots.length, repeatedShots: repeatedShots.length, visualGaps: visualGaps.length, talkingHeadRuns: talkingHeadRuns.length }, longShots, repeatedShots, visualGaps, talkingHeadRuns, audio: { tracks: audioTracks.map((track) => ({ id: track.id, name: track.name, role: track.role || "mix", items: track.items.length })), hasAnchor, hasFollower }, suggestions: [...longShots, ...repeatedShots, ...talkingHeadRuns].sort((a,b)=>a.start-b.start) };
}

export function planVlogRhythm(project, options = {}) {
  const audit = analyzeVlogRhythm(project, options), timeline = activeTimeline(project), pace = audit.pace, cutaways = timeline.tracks.find((track) => track.name === "V2 · Cutaways"), transitionDuration = pace === "energetic" ? .08 : pace === "calm" ? .22 : .14, lead = pace === "energetic" ? .1 : .18, tail = pace === "calm" ? .2 : .12;
  const cutawayUpdates = (cutaways?.items || []).map((item) => { const asset = project.assets.find((entry) => entry.id === item.assetId), nextStart = Math.max(0, item.start - lead), addedLead = item.start - nextStart, room = Math.max(0, Number(asset?.duration || 0) - item.sourceStart - item.duration), addedTail = Math.min(tail, Math.max(0, room - addedLead)); return { itemId: item.id, start: Number(nextStart.toFixed(3)), duration: Number((item.duration + addedLead + addedTail).toFixed(3)), transitionIn: { type: "cross-dissolve", duration: transitionDuration }, transitionOut: { type: "cross-dissolve", duration: transitionDuration }, reason: "visual prelap and soft cutaway handoff" }; });
  const audioTracks = timeline.tracks.filter((track) => track.type === "audio"), voice = audioTracks.find((track) => /voice|natural|narration|dialog|人声|旁白/i.test(track.name)) || audioTracks[0], music = audioTracks.find((track) => /music|音乐/i.test(track.name)) || audioTracks[1], audioTrackUpdates = audioTracks.map((track) => ({ trackId: track.id, role: track.id === voice?.id ? "anchor" : track.id === music?.id ? "follower" : track.role || "mix", denoise: track.id === voice?.id ? true : Boolean(track.denoise), normalizeLufs: track.id === voice?.id ? -16 : track.normalizeLufs ?? null })), audioItemUpdates = audioTracks.flatMap((track) => track.items.map((item) => ({ itemId: item.id, audioFadeIn: Math.min(.12, item.duration / 3), audioFadeOut: Math.min(.18, item.duration / 3) })));
  return { type: "vlog-rhythm-plan", audit, cutawayUpdates, audioTrackUpdates, audioItemUpdates, manualReview: audit.suggestions, summary: { safeChanges: cutawayUpdates.length + audioTrackUpdates.length + audioItemUpdates.length, manualDecisions: audit.suggestions.length, duckingConfigured: Boolean(voice && music) }, nonMutating: true, reviewRequired: true };
}

export function applyVlogRhythm(project, plan) {
  if (plan?.type !== "vlog-rhythm-plan") throw new Error("A reviewed Vlog rhythm plan is required"); const timeline = activeTimeline(project), items = timeline.tracks.flatMap((track) => track.items);
  for (const update of plan.cutawayUpdates || []) { const item = items.find((entry) => entry.id === update.itemId); if (!item) continue; item.start = update.start; item.duration = update.duration; item.transitionIn = update.transitionIn; item.transitionOut = update.transitionOut; item.rhythmDirector = { reason: update.reason }; }
  for (const update of plan.audioTrackUpdates || []) { const track = timeline.tracks.find((entry) => entry.id === update.trackId); if (!track || track.type !== "audio") continue; track.role = update.role; track.denoise = update.denoise; track.normalizeLufs = update.normalizeLufs; }
  for (const update of plan.audioItemUpdates || []) { const item = items.find((entry) => entry.id === update.itemId); if (!item) continue; item.audioFadeIn = update.audioFadeIn; item.audioFadeOut = update.audioFadeOut; }
  timeline.rhythmDirector = { appliedAt: new Date().toISOString(), audit: plan.audit, manualReview: plan.manualReview }; project.history.push({ at: new Date().toISOString(), action: "apply_vlog_rhythm", safeChanges: plan.summary.safeChanges, manualDecisions: plan.summary.manualDecisions }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { audit: plan.audit, summary: plan.summary, validation };
}

const assetText = (asset) => [asset.name, asset.annotation?.description, ...(asset.annotation?.tags || []), ...(asset.annotation?.actions || [])].filter(Boolean).join(" ").toLowerCase();
export function planVlogSound(project, { musicAssetId, sfxAssetIds = [], naturalSound = true, musicVolumeDb = -17, ambienceVolumeDb = -20, sfxVolumeDb = -10 } = {}) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before planning sound design"); const timeline = activeTimeline(project), end = Math.max(0, ...timeline.tracks.flatMap((track) => track.items.map((item) => item.start + item.duration)), ...(timeline.captions?.cues || []).map((cue) => cue.end)); if (!end) throw new Error("Sound design requires an edited timeline");
  const audio = project.assets.filter((asset) => asset.type === "audio" && asset.duration > .1), explicitMusic = audio.filter((asset) => /music|song|score|bgm|音乐|配乐/i.test(assetText(asset))), explicitSfx = audio.filter((asset) => /sfx|sound effect|whoosh|impact|click|hit|transition|音效|转场|呼啸|撞击/i.test(assetText(asset))), music = project.assets.find((asset) => asset.id === musicAssetId) || explicitMusic[0], selectedSfx = sfxAssetIds.length ? sfxAssetIds.map((id) => project.assets.find((asset) => asset.id === id)).filter(Boolean) : explicitSfx;
  const zones = [{ id: "intro", start: 0, end: Math.min(end, end * .1), gain: musicVolumeDb - 2 }, { id: "body", start: end * .1, end: end * .72, gain: musicVolumeDb - 4 }, { id: "payoff", start: end * .72, end: end * .92, gain: musicVolumeDb + 2 }, { id: "outro", start: end * .92, end, gain: musicVolumeDb - 1 }].filter((zone) => zone.end - zone.start > .05), musicItems = [];
  if (music) for (const zone of zones) { let cursor = zone.start; while (cursor < zone.end - .05) { const duration = Math.min(zone.end - cursor, Number(music.duration)); musicItems.push({ assetId: music.id, start: Number(cursor.toFixed(3)), sourceStart: 0, duration: Number(duration.toFixed(3)), volumeDb: zone.gain, audioFadeIn: Math.min(.35, duration / 3), audioFadeOut: Math.min(.45, duration / 3), label: `Music · ${zone.id}`, soundRole: zone.id }); cursor += duration; } }
  const cutaways = timeline.tracks.find((track) => track.name === "V2 · Cutaways")?.items || [], ambienceItems = []; let lastAmbience = -Infinity;
  if (naturalSound) for (const item of cutaways) { const asset = project.assets.find((entry) => entry.id === item.assetId); if (!asset?.hasAudio || item.start - lastAmbience < 2.5) continue; const duration = Math.min(item.duration, 2.4, Math.max(.1, Number(asset.duration) - item.sourceStart)); ambienceItems.push({ assetId: asset.id, start: item.start, sourceStart: item.sourceStart, duration, volumeDb: ambienceVolumeDb, audioFadeIn: .12, audioFadeOut: .25, label: `Natural · ${item.label}`, soundRole: "ambience" }); lastAmbience = item.start; }
  const sfxItems = selectedSfx.slice(0, Math.min(selectedSfx.length, cutaways.length)).map((asset, index) => { const visual = cutaways[index]; const duration = Math.min(Number(asset.duration), 1.5); return { assetId: asset.id, start: Number(Math.max(0, (visual?.start || 0) - .03).toFixed(3)), sourceStart: 0, duration, volumeDb: sfxVolumeDb, audioFadeIn: .01, audioFadeOut: Math.min(.12, duration / 3), label: `SFX · ${asset.name}`, soundRole: "effect", visualItemId: visual?.id || null }; });
  const warnings = []; if (!music) warnings.push({ kind: "missing-music", message: "没有找到明确标注的音乐素材" }); if (!ambienceItems.length) warnings.push({ kind: "missing-ambience", message: "配画素材没有可用原声，建议补环境声" }); if (!sfxItems.length) warnings.push({ kind: "missing-sfx", message: "没有找到明确标注的音效素材" });
  return { type: "vlog-sound-plan", duration: Number(end.toFixed(3)), musicAssetId: music?.id || null, musicItems, ambienceItems, sfxItems, warnings, mix: { voiceRole: "anchor", musicRole: "follower", ambienceRole: "mix", musicVolumeDb, ambienceVolumeDb, sfxVolumeDb }, summary: { musicSegments: musicItems.length, ambienceMoments: ambienceItems.length, effects: sfxItems.length, warnings: warnings.length }, nonMutating: true, reviewRequired: true };
}

export function applyVlogSound(project, plan, { musicTrackName = "A2 · Music", sfxTrackName = "A3 · SFX", ambienceTrackName = "A4 · Natural Sound", replace = true } = {}) {
  if (plan?.type !== "vlog-sound-plan") throw new Error("A reviewed Vlog sound plan is required"); const timeline = activeTimeline(project); const ensure = (name, role) => { let track = timeline.tracks.find((entry) => entry.name === name); if (!track) { track = { id: randomUUID(), name, type: "audio", role, locked: false, muted: false, volumeDb: 0, denoise: false, normalizeLufs: null, items: [] }; timeline.tracks.push(track); } if (track.locked) throw new Error(`Track ${name} is locked`); track.role = role; if (replace) track.items = []; return track; }, musicTrack = ensure(musicTrackName, "follower"), sfxTrack = ensure(sfxTrackName, "mix"), ambienceTrack = ensure(ambienceTrackName, "mix"), toItem = (entry) => ({ id: randomUUID(), ...entry, opacity: 1 }); musicTrack.items.push(...plan.musicItems.map(toItem)); sfxTrack.items.push(...plan.sfxItems.map(toItem)); ambienceTrack.items.push(...plan.ambienceItems.map(toItem)); musicTrack.items.sort((a,b)=>a.start-b.start); sfxTrack.items.sort((a,b)=>a.start-b.start); ambienceTrack.items.sort((a,b)=>a.start-b.start); const voice = timeline.tracks.find((track) => track.type === "audio" && /voice|natural|narration|dialog|人声|旁白/i.test(track.name)); if (voice) { voice.role = "anchor"; voice.denoise = true; voice.normalizeLufs = -16; } timeline.soundDirector = { appliedAt: new Date().toISOString(), summary: plan.summary, warnings: plan.warnings }; project.history.push({ at: new Date().toISOString(), action: "apply_vlog_sound", ...plan.summary }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { musicTrackId: musicTrack.id, sfxTrackId: sfxTrack.id, ambienceTrackId: ambienceTrack.id, musicItems: musicTrack.items.length, soundItems: sfxTrack.items.length + ambienceTrack.items.length, warnings: plan.warnings, validation };
}

export function planVlogFinishing(project, { openingTitle, openingSubtitle = "", cta = "关注我，继续记录", platform = "short-video", bilingual = false } = {}) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before planning finishing"); const timeline = activeTimeline(project), brief = project.videoType.vlog, cues = timeline.captions?.cues || [], vertical = timeline.height > timeline.width, end = Math.max(0, ...timeline.tracks.flatMap((track) => track.items.map((item) => item.start + item.duration)), ...cues.map((cue) => cue.end));
  const captionIssues = cues.flatMap((cue, index) => { const duration = cue.end - cue.start, chars = [...String(cue.text || "")].length, cps = duration > 0 ? chars / duration : Infinity, issues = []; if (chars > 24) issues.push({ cueIndex: index, start: cue.start, kind: "long-caption", value: chars, suggestion: "字幕超过 24 字，建议拆成两条" }); if (cps > 12) issues.push({ cueIndex: index, start: cue.start, kind: "fast-caption", value: Number(cps.toFixed(1)), suggestion: "字幕阅读速度过快，建议延长或精简" }); return issues; });
  const locations = [...new Set(project.assets.flatMap((asset) => asset.annotation?.locations || []))].slice(0, 3), title = String(openingTitle || brief.objective || project.name).trim().slice(0, 40), titleCards = [{ id: "opening", kind: "title", start: 0, duration: Math.min(2.4, Math.max(1.4, end * .08)), title, subtitle: openingSubtitle, placement: "center", editable: true }, ...locations.map((location, index) => ({ id: `location-${index+1}`, kind: "lower-third", start: Number(Math.min(end * (.2 + index * .22), Math.max(0, end - 3)).toFixed(3)), duration: 2.2, title: String(location), subtitle: "", placement: "safe-lower-left", editable: true })), { id: "cta", kind: "info-card", start: Number(Math.max(0, end - 2.8).toFixed(3)), duration: Math.min(2.8, end || 2.8), title: cta, subtitle: "", placement: "center", editable: true }];
  const captionStyle = { template: vertical ? "bold-box" : "minimal", fontSize: vertical ? 54 : 46, secondaryFontSize: vertical ? 34 : 30, bilingual, position: "bottom", margin: vertical ? 190 : 72, maxWidth: Math.round(timeline.width * .84), color: "#ffffff", outlineColor: "#17150f", outlineWidth: 4, backgroundColor: "#17150f", backgroundOpacity: vertical ? .28 : .16, weight: "bold", shadow: true }, safeArea = vertical ? { top: .08, right: .07, bottom: .16, left: .07 } : { top: .06, right: .05, bottom: .09, left: .05 }, markers = titleCards.map((card) => ({ time: card.start, label: `包装 · ${card.title}`, color: card.id === "cta" ? "red" : "purple", titleCardId: card.id }));
  const exportPreset = { platform, aspect: vertical ? "9:16" : "16:9", width: timeline.width, height: timeline.height, fps: timeline.fps, resolution: "original", codec: "h264", audioCodec: "aac", burnCaptions: true, range: "full" }, warnings = []; if (!cues.length) warnings.push({ kind: "missing-captions", message: "当前没有字幕，发布前建议先转录并生成字幕" }); if (!title) warnings.push({ kind: "missing-title", message: "缺少开场标题" }); if (end < 5) warnings.push({ kind: "short-timeline", message: "时间线不足 5 秒，包装节奏可能不适用" });
  return { type: "vlog-finishing-plan", duration: Number(end.toFixed(3)), captionStyle, captionIssues, safeArea, titleCards, markers, exportPreset, warnings, summary: { titleCards: titleCards.length, captionIssues: captionIssues.length, markers: markers.length, warnings: warnings.length }, nonMutating: true, reviewRequired: true };
}

export function applyVlogFinishing(project, plan) {
  if (plan?.type !== "vlog-finishing-plan") throw new Error("A reviewed Vlog finishing plan is required"); const timeline = activeTimeline(project); timeline.captions ||= { enabled: true, cues: [], style: {} }; timeline.captions.style = { ...(timeline.captions.style || {}), ...plan.captionStyle }; timeline.settings ||= {}; timeline.settings.safeArea = plan.safeArea; timeline.exportPreset = plan.exportPreset; timeline.pendingTitleCards = plan.titleCards; timeline.markers ||= []; const existing = new Set(timeline.markers.filter((marker) => marker.finishingDirector).map((marker) => marker.titleCardId)); timeline.markers.push(...plan.markers.filter((marker) => !existing.has(marker.titleCardId)).map((marker) => ({ id: randomUUID(), ...marker, finishingDirector: true }))); let titleTrack = timeline.tracks.find((track) => track.name === "V3 · Titles"); if (!titleTrack) { titleTrack = { id: randomUUID(), name: "V3 · Titles", type: "video", locked: false, muted: false, opacity: 1, items: [] }; timeline.tracks.push(titleTrack); } timeline.finishingDirector = { appliedAt: new Date().toISOString(), captionIssues: plan.captionIssues, pendingTitleCards: plan.titleCards.length, warnings: plan.warnings }; project.history.push({ at: new Date().toISOString(), action: "apply_vlog_finishing", ...plan.summary }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { titleTrackId: titleTrack.id, pendingTitleCards: plan.titleCards, captionStyle: timeline.captions.style, safeArea: plan.safeArea, exportPreset: plan.exportPreset, markers: plan.markers.length, warnings: plan.warnings, validation };
}

function titleCardSvg(kind, width, height) {
  const lower = kind === "lower-third", boxY = lower ? Math.round(height * .68) : Math.round(height * .36), boxH = lower ? Math.round(height * .18) : Math.round(height * .28), boxX = Math.round(width * .07), boxW = Math.round(width * .86), titleY = boxY + Math.round(boxH * .48), subtitleY = boxY + Math.round(boxH * .74), titleSize = lower ? Math.round(width * .055) : Math.round(width * .072), subtitleSize = Math.round(width * .035);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect x="${boxX}" y="${boxY}" width="${boxW}" height="${boxH}" rx="${Math.round(width*.025)}" fill="{{background}}" fill-opacity="0.88"/><rect x="${boxX}" y="${boxY}" width="${Math.round(width*.016)}" height="${boxH}" rx="${Math.round(width*.008)}" fill="{{accent}}"/><text x="${boxX+Math.round(width*.055)}" y="${titleY}" fill="{{textColor}}" font-family="Arial Unicode MS,Arial,sans-serif" font-size="${titleSize}" font-weight="800">{{title}}</text><text x="${boxX+Math.round(width*.055)}" y="${subtitleY}" fill="{{secondaryColor}}" font-family="Arial Unicode MS,Arial,sans-serif" font-size="${subtitleSize}">{{subtitle}}</text></svg>`;
}

export function renderVlogTitleCards(project, projectPath, { trackName = "V3 · Titles", accent = "#e5484d", background = "#17150f", textColor = "#ffffff", secondaryColor = "#e4dac7", replace = true } = {}) {
  const timeline = activeTimeline(project), cards = timeline.pendingTitleCards || []; if (!cards.length) throw new Error("Apply a Vlog finishing plan before rendering title cards"); let track = timeline.tracks.find((entry) => entry.name === trackName); if (!track) { track = { id: randomUUID(), name: trackName, type: "video", locked: false, muted: false, opacity: 1, items: [] }; timeline.tracks.push(track); } if (track.locked) throw new Error(`Track ${trackName} is locked`); if (replace) track.items = track.items.filter((item) => !item.finishingTitleCard);
  const ordered = [...cards].sort((a,b)=>a.start-b.start), folder = join(dirname(projectPath), "mycut-assets", "vlog-titles"), rendered = [];
  for (const [index, card] of ordered.entries()) { const next = ordered[index+1], duration = Math.min(Number(card.duration), next ? Math.max(0, next.start-card.start-.05) : Number(card.duration)); if (duration < .2) { rendered.push({ titleCardId: card.id, skipped: true, reason: "overlap leaves no safe duration" }); continue; } const id = randomUUID(), source = titleCardSvg(card.kind, timeline.width, timeline.height), properties = [{ key: "title", label: "标题", type: "text", defaultValue: card.title }, { key: "subtitle", label: "副标题", type: "text", defaultValue: card.subtitle || "" }, { key: "accent", label: "强调色", type: "color", defaultValue: accent }, { key: "background", label: "背景色", type: "color", defaultValue: background }, { key: "textColor", label: "文字色", type: "color", defaultValue: textColor }, { key: "secondaryColor", label: "副文字色", type: "color", defaultValue: secondaryColor }], values = { title: card.title, subtitle: card.subtitle || "", accent, background, textColor, secondaryColor }, sourcePath = join(folder, `${id}.svg`), outputPath = join(folder, `${id}.png`); renderSvgMotionGraphic({ source, properties, values, width: timeline.width, height: timeline.height, sourcePath, outputPath }); const asset = { id, path: outputPath, sourcePath, name: `Vlog ${card.kind} · ${card.title}`, description: `Editable Vlog finishing card ${card.id}`, type: "motion-graphic", duration: null, width: timeline.width, height: timeline.height, motionGraphic: { engine: "svg", source, properties, values }, finishingTitleCard: card.id }; project.assets.push(asset); const item = { id: randomUUID(), assetId: id, start: card.start, sourceStart: 0, duration, volumeDb: 0, opacity: 1, label: card.title, finishingTitleCard: card.id, fadeIn: .18, fadeOut: .18 }; track.items.push(item); rendered.push({ titleCardId: card.id, assetId: id, itemId: item.id, sourcePath, outputPath, start: item.start, duration }); }
  track.items.sort((a,b)=>a.start-b.start); timeline.pendingTitleCards = cards.map((card) => ({ ...card, status: rendered.find((entry) => entry.titleCardId === card.id)?.skipped ? "blocked" : "rendered" })); project.history.push({ at: new Date().toISOString(), action: "render_vlog_title_cards", rendered: rendered.filter((entry) => !entry.skipped).length, skipped: rendered.filter((entry) => entry.skipped).length }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { trackId: track.id, rendered, validation };
}

export function analyzeVlogRelease(project, { requireCaptions = true, maxVideoGap = .25 } = {}) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before release preflight"); const timeline = activeTimeline(project), validation = validateProject(project), referencedIds = new Set(timeline.tracks.flatMap((track) => track.items.map((item) => item.assetId))), offline = project.assets.filter((asset) => referencedIds.has(asset.id) && !existsSync(asset.path)).map((asset) => ({ assetId: asset.id, name: asset.name, path: asset.path, items: timeline.tracks.flatMap((track) => track.items.filter((item) => item.assetId === asset.id).map((item) => ({ track: track.name, itemId: item.id, start: item.start }))) })), blockers = [], warnings = [], safeFixes = [];
  blockers.push(...validation.errors.map((message) => ({ kind: "project-invalid", message }))); if (offline.length) blockers.push({ kind: "offline-assets", message: `${offline.length} 个时间线素材离线`, details: offline });
  const primary = timeline.tracks.find((track) => track.name === "V1 · Story") || timeline.tracks.find((track) => track.type === "video"), primaryItems = [...(primary?.items || [])].sort((a,b)=>a.start-b.start), duration = Math.max(0, ...timeline.tracks.flatMap((track) => track.items.map((item) => item.start+item.duration))); if (!primaryItems.length) blockers.push({ kind: "missing-primary-video", message: "主故事轨没有画面" }); else { if (primaryItems[0].start > maxVideoGap) blockers.push({ kind: "opening-black", message: `开头有 ${primaryItems[0].start.toFixed(2)} 秒无主画面`, start: 0, end: primaryItems[0].start }); for (let i=1;i<primaryItems.length;i++) { const gap = primaryItems[i].start-(primaryItems[i-1].start+primaryItems[i-1].duration); if (gap > maxVideoGap) blockers.push({ kind: "video-gap", message: `主故事轨有 ${gap.toFixed(2)} 秒空档`, start: primaryItems[i-1].start+primaryItems[i-1].duration, end: primaryItems[i].start }); } }
  const pending = (timeline.pendingTitleCards || []).filter((card) => card.status !== "rendered"); if (pending.length) blockers.push({ kind: "unrendered-titles", message: `${pending.length} 张标题卡尚未渲染`, details: pending.map((card) => card.id) }); const cues = timeline.captions?.cues || []; if (requireCaptions && project.videoType.vlog.narration !== "none" && !cues.length) blockers.push({ kind: "missing-captions", message: "有旁白但没有字幕" });
  const captionIssues = cues.flatMap((cue, index) => { const chars = [...String(cue.text || "")].length, seconds = cue.end-cue.start, cps = seconds > 0 ? chars/seconds : Infinity; return cps > 12 || chars > 24 ? [{ cueIndex: index, start: cue.start, chars, cps: Number(cps.toFixed(1)) }] : []; }); if (captionIssues.length) warnings.push({ kind: "caption-readability", message: `${captionIssues.length} 条字幕可能难以阅读`, details: captionIssues }); const target = Number(project.videoType.vlog.targetDuration || 0), deviation = target ? Math.abs(duration-target)/target : 0; if (target && deviation > .2) warnings.push({ kind: "duration-deviation", message: `成片 ${duration.toFixed(1)} 秒，与目标 ${target.toFixed(1)} 秒偏差 ${Math.round(deviation*100)}%` }); warnings.push(...validation.warnings.map((message) => ({ kind: "project-warning", message })));
  const audioTracks = timeline.tracks.filter((track) => track.type === "audio"), voice = audioTracks.find((track) => /voice|natural|narration|dialog|人声|旁白/i.test(track.name)), music = audioTracks.find((track) => /music|音乐/i.test(track.name)); if (voice && voice.role !== "anchor") safeFixes.push({ kind: "voice-anchor", trackId: voice.id, message: "把人声轨设为 Anchor" }); if (music && music.role !== "follower") safeFixes.push({ kind: "music-follower", trackId: music.id, message: "把音乐轨设为 Follower 以自动避让人声" }); if (!timeline.settings?.safeArea) safeFixes.push({ kind: "safe-area", message: "写入平台安全区" }); if (!timeline.exportPreset) safeFixes.push({ kind: "export-preset", message: "写入发布导出预设" }); if (cues.length && timeline.captions?.enabled === false) safeFixes.push({ kind: "enable-captions", message: "启用已有字幕" }); if (!voice) warnings.push({ kind: "missing-voice-track", message: "没有识别到人声轨" }); if (!music) warnings.push({ kind: "missing-music-track", message: "没有识别到音乐轨" });
  const score = Math.max(0, Math.round(100-blockers.length*25-warnings.length*6-safeFixes.length*3)); return { type: "vlog-release-preflight", ready: blockers.length === 0, score, duration: Number(duration.toFixed(3)), targetDuration: target, blockers, warnings, safeFixes, offlineAssets: offline, validation, checkedAt: new Date().toISOString() };
}

export function applyVlogReleaseFixes(project, preflight) {
  if (preflight?.type !== "vlog-release-preflight") throw new Error("A Vlog release preflight is required"); const timeline = activeTimeline(project), applied = []; for (const fix of preflight.safeFixes || []) { if (fix.kind === "voice-anchor" || fix.kind === "music-follower") { const track = timeline.tracks.find((entry) => entry.id === fix.trackId); if (track) { track.role = fix.kind === "voice-anchor" ? "anchor" : "follower"; applied.push(fix.kind); } } else if (fix.kind === "safe-area") { timeline.settings ||= {}; timeline.settings.safeArea = timeline.height > timeline.width ? { top:.08,right:.07,bottom:.16,left:.07 } : { top:.06,right:.05,bottom:.09,left:.05 }; applied.push(fix.kind); } else if (fix.kind === "export-preset") { timeline.exportPreset = { platform:"short-video",aspect:timeline.height>timeline.width?"9:16":"16:9",width:timeline.width,height:timeline.height,fps:timeline.fps,resolution:"original",codec:"h264",audioCodec:"aac",burnCaptions:true,range:"full" }; applied.push(fix.kind); } else if (fix.kind === "enable-captions") { timeline.captions.enabled = true; applied.push(fix.kind); } } timeline.releasePreflight = { fixedAt: new Date().toISOString(), applied, previousScore: preflight.score }; project.history.push({ at:new Date().toISOString(),action:"apply_vlog_release_fixes",applied }); const validation=validateProject(project); if(!validation.valid)throw new Error(validation.errors.join("\n")); return { applied, remaining: analyzeVlogRelease(project), validation };
}

export function analyzeVlogWorkflow(project) {
  if (project.videoType?.id !== "vlog") throw new Error("Select the Vlog video type before reading workflow status"); const timeline = activeTimeline(project), story = timeline.tracks.find((track) => track.name === "V1 · Story"), broll = timeline.tracks.find((track) => track.name === "V2 · Cutaways"), titles = timeline.tracks.find((track) => track.name === "V3 · Titles"), referenced = new Set(timeline.tracks.flatMap((track) => track.items.map((item) => item.assetId))), onlineReferenced = [...referenced].filter((id) => { const asset = project.assets.find((entry) => entry.id === id); return asset && existsSync(asset.path); }).length, release = analyzeVlogRelease(project), cards = timeline.pendingTitleCards || [];
  const stages = [
    { id:"setup",label:"Vlog 设置",complete:Boolean(project.videoType?.vlog),detail:project.videoType.vlog?.objective||"已选择 Vlog" },
    { id:"media",label:"素材在线",complete:referenced.size>0&&onlineReferenced===referenced.size,detail:`${onlineReferenced}/${referenced.size} 个引用素材在线` },
    { id:"captions",label:"字幕与旁白",complete:project.videoType.vlog.narration==="none"||Boolean(timeline.captions?.cues?.length),detail:`${timeline.captions?.cues?.length||0} 条字幕` },
    { id:"story",label:"主故事初剪",complete:Boolean(story?.items.length),detail:`${story?.items.length||0} 个主镜头` },
    { id:"broll",label:"旁白配画",complete:Boolean(broll?.items.length),detail:`${broll?.items.length||0} 个 B-roll` },
    { id:"rhythm",label:"节奏导演",complete:Boolean(timeline.rhythmDirector),detail:timeline.rhythmDirector?"已应用节奏方案":"尚未应用" },
    { id:"sound",label:"声音导演",complete:Boolean(timeline.soundDirector),detail:timeline.soundDirector?"已写入声音方案":"尚未写入" },
    { id:"finishing",label:"成片包装",complete:Boolean(timeline.finishingDirector),detail:timeline.finishingDirector?"字幕、安全区与包装已应用":"尚未应用" },
    { id:"titles",label:"MG 标题",complete:cards.length>0&&cards.every((card)=>card.status==="rendered")&&Boolean(titles?.items.some((item)=>item.finishingTitleCard)),detail:`${cards.filter((card)=>card.status==="rendered").length}/${cards.length} 张已渲染` },
    { id:"release",label:"发布总检",complete:release.ready,detail:release.ready?"所有阻断项已清除":`${release.blockers.length} 个阻断项` },
  ];
  const routes = { media:{ tool:"relink_missing_from_folder",instruction:"导入或重新链接时间线使用的素材" }, captions:{ tool:"transcribe_local",instruction:"转录旁白并生成字幕" }, story:{ tool:"plan_vlog_edit",instruction:"生成并确认主故事初剪" }, broll:{ tool:"plan_vlog_narration_broll",instruction:"按旁白生成并确认 B-roll" }, rhythm:{ tool:"plan_vlog_rhythm",instruction:"检查并应用安全节奏优化" }, sound:{ tool:"plan_vlog_sound",instruction:"生成并写入声音方案" }, finishing:{ tool:"plan_vlog_finishing",instruction:"生成并应用成片包装" }, titles:{ tool:"render_vlog_title_cards",instruction:"渲染可编辑 MG 标题" }, release:{ tool:"analyze_vlog_release",instruction:"清除发布总检阻断项" } }, next = stages.find((stage)=>!stage.complete), completed = stages.filter((stage)=>stage.complete).length;
  return { type:"vlog-workflow-status",progress:Math.round(completed/stages.length*100),completed,total:stages.length,stages,nextAction:next?{ stage:next.id,label:next.label,...routes[next.id] }: { stage:"export",label:"导出",tool:"submit_vlog_release_export",instruction:"项目已通过总检，可以提交发布导出" },readyToExport:release.ready,release };
}

export function analyzeVlogCoverage(project) {
  const brief = project.videoType?.vlog;
  if (project.videoType?.id !== "vlog" || !brief) throw new Error("Select the Vlog video type before analyzing coverage");
  const pool = candidates(project);
  const coverage = sections.map((section) => {
    const ranked = pool.map((entry) => scoreForSection(entry, section, brief.pace)).sort((a,b)=>b.score-a.score||a.entry.name.localeCompare(b.entry.name));
    const exact = ranked.filter((entry) => entry.matches.length > 0);
    const status = exact.length >= 2 ? "ready" : exact.length === 1 ? "thin" : "missing";
    return { id: section.id, label: section.label, status, candidateCount: ranked.length, exactMatches: exact.length, suggestion: status === "ready" ? null : sectionSuggestions[section.id], strongest: ranked.slice(0, 3).map(({ entry, matches, score }) => ({ assetId: entry.asset.id, subclipId: entry.id === entry.asset.id ? null : entry.id, name: entry.name, sourceStart: entry.sourceStart, duration: entry.duration, matches, score: Number(score.toFixed(3)) })) };
  });
  const summary = { ready: coverage.filter((entry) => entry.status === "ready").length, thin: coverage.filter((entry) => entry.status === "thin").length, missing: coverage.filter((entry) => entry.status === "missing").length };
  return { type: "vlog-coverage", assets: project.assets.filter((asset) => ["video","image"].includes(asset.type)).length, candidates: pool.length, sections: coverage, summary, readyToPlan: pool.length > 0, suggestions: coverage.filter((entry) => entry.suggestion).map((entry) => ({ section: entry.id, text: entry.suggestion })) };
}

export function planVlogEdit(project, { targetDuration, pace, start = 0, includeAssetIds = [], excludeAssetIds = [] } = {}) {
  const brief = project.videoType?.vlog; if (project.videoType?.id !== "vlog" || !brief) throw new Error("Select the Vlog video type before planning a Vlog edit");
  const target = Number(targetDuration ?? brief.targetDuration), rhythm = pace || brief.pace; if (!(target >= 10 && target <= 3600)) throw new Error("Vlog target duration must be 10-3600 seconds"); if (!paceRanges[rhythm]) throw new Error(`Unsupported Vlog pace: ${rhythm}`);
  const include = new Set(includeAssetIds), exclude = new Set(excludeAssetIds), pool = candidates(project).filter((entry) => !exclude.has(entry.asset.id) && (!include.size || include.has(entry.asset.id))); if (!pool.length) throw new Error("Vlog planning requires at least one video or image asset");
  const [minShot, maxShot] = paceRanges[rhythm], used = new Map(), shots = []; let cursor = Number(start), shotIndex = 0;
  for (const section of sections) {
    const sectionDuration = section.id === 'outro' ? Math.max(0, start + target - cursor) : target * section.ratio, sectionEnd = cursor + sectionDuration;
    while (cursor < sectionEnd - .05) {
      const ranked = pool.map((entry) => { const scored = scoreForSection(entry, section, rhythm), repeats = used.get(entry.asset.id) || 0; return { entry, score: scored.score - repeats * .65 - (shots.at(-1)?.assetId === entry.asset.id ? 1.4 : 0) }; }).sort((a,b)=>b.score-a.score||a.entry.name.localeCompare(b.entry.name));
      const chosen = ranked[0].entry, desired = minShot + (maxShot - minShot) * (((shotIndex * 7) % 5) / 4), duration = Math.min(sectionEnd - cursor, desired, chosen.duration), sourceRoom = Math.max(0, chosen.duration - duration), sourceStart = chosen.sourceStart + (sourceRoom ? ((shotIndex * .37) % 1) * sourceRoom : 0);
      if (duration < .2) break; shots.push({ assetId: chosen.asset.id, subclipId: chosen.id === chosen.asset.id ? null : chosen.id, start: Number(cursor.toFixed(3)), sourceStart: Number(sourceStart.toFixed(3)), duration: Number(duration.toFixed(3)), section: section.id, sectionLabel: section.label, label: chosen.name, reason: ranked[0].score > .5 ? `matched ${section.label.toLowerCase()} role` : `best available ${section.label.toLowerCase()} shot` });
      cursor += duration; shotIndex++; used.set(chosen.asset.id, (used.get(chosen.asset.id) || 0) + 1);
    }
  }
  const coverage = analyzeVlogCoverage(project);
  return { type: "vlog", style: brief.style, pace: rhythm, targetDuration: target, start, duration: Number((cursor - start).toFixed(3)), shots, sections: sections.map((section) => ({ id: section.id, label: section.label, shots: shots.filter((shot) => shot.section === section.id).length })), assetsUsed: [...new Set(shots.map((shot) => shot.assetId))], coverage, warnings: coverage.suggestions, nonMutating: true, reviewRequired: true };
}

export function applyVlogEdit(project, plan, { trackName = "V1 · Story", replace = true } = {}) {
  if (plan?.type !== "vlog" || !Array.isArray(plan.shots) || !plan.shots.length) throw new Error("A reviewed Vlog plan is required"); const timeline = activeTimeline(project); let track = timeline.tracks.find((entry) => entry.name === trackName); if (!track) { track = { id: randomUUID(), name: trackName, type: "video", locked: false, muted: false, opacity: 1, items: [] }; timeline.tracks.push(track); } if (track.locked) throw new Error(`Track ${trackName} is locked`); if (replace) track.items = [];
  track.items.push(...plan.shots.map((shot) => ({ id: randomUUID(), assetId: shot.assetId, start: shot.start, sourceStart: shot.sourceStart, duration: shot.duration, volumeDb: 0, opacity: 1, label: `${shot.sectionLabel}: ${shot.label}`, vlogSection: shot.section }))); track.items.sort((a,b)=>a.start-b.start); project.history.push({ at: new Date().toISOString(), action: "apply_vlog_edit", shots: plan.shots.length, duration: plan.duration }); const validation = validateProject(project); if (!validation.valid) throw new Error(validation.errors.join("\n")); return { trackId: track.id, trackName, items: track.items, validation };
}
